jwt:
  secret: Th!$1$T@kEn
  expirationMs: 3600000 # 1 hour

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  enable-native-support: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snapboxtest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true