jwt:
  secret: Th!$1$T@kEn
  expirationMs: 3600000 # 1 hour

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  enable-native-support: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snapboxtest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: admin
#    password: admin
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true